name: Import File from URL

on:
  workflow_dispatch: # 手动触发工作流

jobs:
  import-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download file from URL
      run: |
        wget -O novaAnimeXL_ilV125.safetensors 'https://civitai-delivery-worker-prod.5ac0637cfd0766c97916cefa3764fbdf.r2.cloudflarestorage.com/model/2515131/novaanimeilv125.N3BI.safetensors?X-Amz-Expires=86400&response-content-disposition=attachment%3B%20filename%3D%22novaAnimeXL_ilV125.safetensors%22&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=e01358d793ad6966166af8b3064953ad/20251105/us-east-1/s3/aws4_request&X-Amz-Date=20251105T141541Z&X-Amz-SignedHeaders=host&X-Amz-Signature=fdf3b51ff43e39fccfff281911c5e829335081bfd2cfc35c9148f631c4e9925a'

    - name: Commit and push file
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add novaAnimeXL_ilV125.safetensors
        git commit -m "Add file from link"
        git push origin main
